import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">CovidSearch</Link>
        </li>
        <li>
          <Link to="/covidsearchvarients">CovidSearchvarients</Link>
        </li>
        <li>
          <Link to="/covidstate">CovidState</Link>
        </li>
        <li>
          <Link to="/covidselect">CovidSelect</Link>
        </li>
        <li>
          <Link to="/covidbargraphs">CovidBargraphs</Link>
        </li>
        <li>
          <Link to="/covidabout">CovidAbout</Link>
        </li>
        <li>
          <Link to="/coviderror">CovidError</Link>
        </li>
        <li>
          <Link to="/vaccine">Vaccine</Link>
        </li>
        <li>
          <Link to="/covid2state">Covid2State</Link>
        </li>
        <li>
          <Link to="/vaccineone">VaccineOne</Link>
        </li>
        <li>
          <Link to="/vaccinedropdown">Vaccinedropdown</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
